# Generated by Django 5.0.6 on 2024-06-27 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-request_date']},
        ),
        migrations.AddField(
            model_name='movie',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
