# Generated by Django 5.0.6 on 2024-06-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-request_date'], 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, default=None, related_name='requests', through='movieapp.Request', to='movieapp.movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlisted',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlisted', to='movieapp.movie'),
        ),
    ]
