# Generated by Django 5.0.6 on 2024-07-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movieapp.movie'),
        ),
        migrations.AlterField(
            model_name='request',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='movieapp.profile'),
        ),
    ]
