# Generated by Django 5.0.6 on 2024-07-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_alter_profile_requests_alter_request_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciccio', to='movieapp.movie'),
        ),
        migrations.AlterField(
            model_name='request',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciccio', to='movieapp.profile'),
        ),
    ]
