# Generated by Django 5.0.6 on 2024-07-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_alter_request_movie_alter_request_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, default=None, related_name='requests', through='movieapp.Request', to='movieapp.movie'),
        ),
        migrations.AlterField(
            model_name='request',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movieapp.movie'),
        ),
        migrations.AlterField(
            model_name='request',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='movieapp.profile'),
        ),
    ]
