# Generated by Django 5.0.6 on 2024-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_alter_profile_requests_alter_request_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, default=None, related_name='requested_by', through='movieapp.Request', to='movieapp.movie'),
        ),
    ]
