# Generated by Django 5.0.6 on 2024-07-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0012_alter_profile_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_requests', to='movieapp.movie'),
        ),
    ]
