# Generated by Django 5.0.6 on 2024-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_alter_request_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='propic',
            field=models.ImageField(blank=True, default='static\\unknown_user.png', upload_to='profilepictures/'),
        ),
    ]
